-- BELOW USES CIW FOR EMP STATUS --
-- OPEN NOTES:
	-- What about Leave > 1 Year?
	-- What about Leave with expiration of 3999-09-09 00:00:00.000?

	WITH
		LWOP_01 AS
		(SELECT DISTINCT 
				  EMPLOYEE_ID AS EID
				, CAST(JOB_EMPLMNT_STATUS_CODE AS VARCHAR(2)) AS JOB_EMPLMNT_STATUS_CODE
				, row_number() 
					OVER(
						PARTITION BY EMPLOYEE_ID ORDER BY EMPLOYEE_ID, JOB_EFFECTIVE_DATE
						) 
					AS LEAVERECORD
				, CAST(EXTRACT(MONTH FROM JOB_EFFECTIVE_DATE) AS NUMBER(2,0)) AS EFFECTIVE_MONTH
				, CAST(EXTRACT(YEAR FROM JOB_EFFECTIVE_DATE) AS NUMBER(4,0)) AS EFFECTIVE_YEAR
				, CAST(EXTRACT(MONTH FROM JOB_EXPIRATION_DATE) AS NUMBER(2,0)) AS EXPIRE_MONTH
				, CAST(EXTRACT(YEAR FROM JOB_EXPIRATION_DATE) AS NUMBER(4,0)) AS EXPIRE_YEAR
				, CASE 
					WHEN EXTRACT(MONTH FROM JOB_EFFECTIVE_DATE)
						BETWEEN 1 AND 7 
					THEN 'SPRING'
					ELSE 'FALL'
				END AS SEMESTER				
				, CASE 
					WHEN EXTRACT(MONTH FROM JOB_EFFECTIVE_DATE)
						BETWEEN 1 AND 7 
						THEN 
						/* Academic Year is prior calendar year if Spring Term */
							CONCAT(CONCAT(CAST((EXTRACT(YEAR FROM JOB_EFFECTIVE_DATE) - 1) AS VARCHAR(10))
							, ' - ')
							, 	   CAST((EXTRACT(YEAR FROM JOB_EFFECTIVE_DATE)) AS VARCHAR(10)))
					WHEN EXTRACT(MONTH FROM JOB_EFFECTIVE_DATE)
						BETWEEN 8 AND 12 
						THEN 
							CONCAT(CONCAT(CAST((EXTRACT(YEAR FROM JOB_EFFECTIVE_DATE))AS VARCHAR(10)) 
							, ' - ')
							,CAST((EXTRACT(YEAR FROM JOB_EFFECTIVE_DATE) + 1)AS VARCHAR(10)) )
					END AS AY
				, JOB_EXPIRATION_DATE - JOB_EFFECTIVE_DATE AS Duration_Days
				, ROUND(((JOB_EXPIRATION_DATE - JOB_EFFECTIVE_DATE) / 365),3) AS Annual_Rate
				, CASE
				    WHEN ROUND(((JOB_EXPIRATION_DATE - JOB_EFFECTIVE_DATE) / 365), 3) < 0.17 -- Less than 2 mo should be 0
				        THEN 0
				    WHEN ROUND(((JOB_EXPIRATION_DATE - JOB_EFFECTIVE_DATE) / 365), 3) BETWEEN 0.17 AND 0.594 -- BETWEEN 2 MONTHs AND 7 months round to 0.5
				        THEN 0.5
				    WHEN ROUND(((JOB_EXPIRATION_DATE - JOB_EFFECTIVE_DATE) / 365), 3) BETWEEN 0.595 AND 1.17 -- BETWEEN 7 months AND one YEAR rounded TO 1
				        THEN 1
				    WHEN ROUND(((JOB_EXPIRATION_DATE - JOB_EFFECTIVE_DATE) / 365), 3) BETWEEN 1.17 AND 1.594 -- BETWEEN 1 YEAR AND 1 YEAR 7 MONTHS round to 1.5
				        THEN 1.5
				    WHEN ROUND(((JOB_EXPIRATION_DATE - JOB_EFFECTIVE_DATE) / 365), 3) BETWEEN 1.595 AND 2.17 -- BETWEEN 1 YEAR 7 MONTHS AND 2 YEARS rounded TO 2
				        THEN 2
				    WHEN ROUND(((JOB_EXPIRATION_DATE - JOB_EFFECTIVE_DATE) / 365), 3) BETWEEN 2.17 AND 2.594 -- BETWEEN 2 YEARS AND 2 YEARS 7 MONTHS round to 2.5
				        THEN 2.5
				    WHEN ROUND(((JOB_EXPIRATION_DATE - JOB_EFFECTIVE_DATE) / 365), 3) BETWEEN 2.595 AND 3.17 -- BETWEEN 2 YEARS 7 MONTHS AND 3 YEARS rounded TO 3
				        THEN 3
				    WHEN ROUND(((JOB_EXPIRATION_DATE - JOB_EFFECTIVE_DATE) / 365), 3) BETWEEN 3.17 AND 3.594 -- BETWEEN 3 YEARS AND 3 YEARS 7 MONTHS round to 3.5
				        THEN 3.5
				    WHEN ROUND(((JOB_EXPIRATION_DATE - JOB_EFFECTIVE_DATE) / 365), 3) BETWEEN 3.595 AND 4.17 -- BETWEEN 3 YEARS 7 MONTHS AND 4 YEARS rounded TO 4
				        THEN 4
				    WHEN ROUND(((JOB_EXPIRATION_DATE - JOB_EFFECTIVE_DATE) / 365), 3) BETWEEN 4.17 AND 4.594 -- BETWEEN 4 YEARS AND 4 YEARS 7 MONTHS round to 4.5
				        THEN 4.5
				    WHEN ROUND(((JOB_EXPIRATION_DATE - JOB_EFFECTIVE_DATE) / 365), 3) BETWEEN 4.595 AND 5.17 -- BETWEEN 4 YEARS AND 4 YEARS 7 MONTHS round to 4.5
				        THEN 5
				END AS ROUNDED_ANNUAL_RATE
			    , JOB_EFFECTIVE_DATE
			    , JOB_EXPIRATION_DATE
				, JOB_POSITION_NUM
			    , JOB_JB_CODE
			    , JOB_DEPT_ID
			FROM artemis.HRMS_JOB_TBL
			WHERE JOB_EMPLMNT_STATUS_CODE IN ('L') -- LWOP
				AND JOB_JB_CODE IN ('1100', '1101' ,'1102' ,'1103')
			ORDER BY EMPLOYEE_ID, LEAVERECORD
		)
SELECT * FROM LWOP_01;
